env_config:
  env_name: rodent
  task_name: bowl_escape
  walker_name: rodent
  render_camera_name: close_profile

  env_args:
    # pending, now it is still using the default env args

network_config:
  arch_name: intention
  encoder_layer_sizes: [256,256,256]
  decoder_layer_sizes: [512, 512, 512]
  critic_layer_sizes: [512, 512, 512]
  intention_size: 60
  kl_schedule: True # Whether to use a ramping KL schedule
  kl_weight: 1e-3 # The maximum weight if schedule is True

train_setup:
  agent_name: rodent
  run_name: bowl_escape
  checkpoint_to_restore: /root/vast/scott-yang/track-mjx/model_checkpoints/250512_182657
  freeze_decoder: True
  checkpoint_max_to_keep:
  checkpoint_keep_period:
  eval_every: 5_000_000
  reset_every: 50_000_000
  ppo_params:
    episode_length: 1000
    num_envs: 2048
    num_timesteps: 1_000_000_000
    batch_size: 1024
    num_minibatches: 8
    num_updates_per_batch: 4
    learning_rate: 1e-4
    clipping_epsilon: 0.2
    discounting: 0.95
    action_repeat: 1
    entropy_cost: 1e-2
    reward_scaling: 1
    normalize_observations: True
    unroll_length: 20
    seed: 0

logging_config:
  project_name: vnl_playground
  group_name:
  model_path: model_checkpoints
  algo_name: ppo

walker_config:
  torque_actuators: False
  rescale_factor: 0.8
  joint_names:
    - vertebra_1_extend
    - hip_L_supinate
    - hip_L_abduct
    - hip_L_extend
    - knee_L
    - ankle_L
    - toe_L
    - hip_R_supinate
    - hip_R_abduct
    - hip_R_extend
    - knee_R
    - ankle_R
    - toe_R
    - vertebra_C11_extend
    - vertebra_cervical_1_bend
    - vertebra_axis_twist
    - atlas
    - mandible
    - scapula_L_supinate
    - scapula_L_abduct
    - scapula_L_extend
    - shoulder_L
    - shoulder_sup_L
    - elbow_L
    - wrist_L
    - scapula_R_supinate
    - scapula_R_abduct
    - scapula_R_extend
    - shoulder_R
    - shoulder_sup_R
    - elbow_R
    - wrist_R
    - finger_R
  body_names:
    - torso
    - pelvis
    - upper_leg_L
    - lower_leg_L
    - foot_L
    - upper_leg_R
    - lower_leg_R
    - foot_R
    - skull
    - jaw
    - scapula_L
    - upper_arm_L
    - lower_arm_L
    - finger_L
    - scapula_R
    - upper_arm_R
    - lower_arm_R
    - finger_R
  end_eff_names:
    - foot_L
    - foot_R
    - hand_L
    - hand_R
    - skull
